# Generated by Django 6.1.1 on 2026-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(2, 'In progress'), (1, 'Completed')], default=2),
        ),
    ]
